spring:
  cloud:
    # spring cloud gateway 路由配置方式
    gateway:
      # 是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。
      # 默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
      discovery:
        # 路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
        locator:
          enabled: true
      routes:
        - id: ORDER-SERVICE           #网关路由到订单服务order-service
          uri: http://localhost:8081/
          predicates:
            - Path=/ORDER-SERVICE/**
#      - id: USER-SERVICE            #网关路由到用户服务user-service
#        uri: lb://USER-SERVICE
#        predicates:
#          - Pach=/USER-SERVICE/**

server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.hostname}
logging:
  level:
    com.sparrow:  debug

feign:
  hystrix:
    enabled: true
