server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.hostname}
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 25
      connection-timeout: 30000
      idle-timeout: 30000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.89:3306/db1?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=TRUE

logging:
  level:
    com.sparrow: debug