server:
  port: 10000

spring:
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    hostname: localhost
    metadata-map:
      user.name: admin
      user.password: admin
    health-check-url-path: /actuator/health
    home-page-url-path: /actuator
    status-page-url-path: /actuator/info
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/


# 暴露服务信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 日志
logging:
  level:
    com.sparrow: debug

